apiVersion: v1
kind: Service
metadata:
  name: {{include "greetingsapp-chart.fullname" .}}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    instance: {{ .Release.Name }}
    managed-by: {{ .Release.ServiceName }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.internalPort }}
    protocol: TCP
    name: {{ .Values.service.name }}
  selector:
    app: {{include "greetingsapp-chart.name" .}}
    instance: {{ .Release.Name }}